# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180306_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='cover',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(default='', upload_to='goods/images', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='image',
            field=models.ImageField(max_length=200, upload_to='brands/images', verbose_name='品牌图片'),
        ),
    ]
