# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180404_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='banners', verbose_name='图片'),
        ),
    ]
