# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180406_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='品牌描述', null=True, verbose_name='品牌描述'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='name',
            field=models.CharField(blank=True, default='', help_text='品牌名', max_length=30, null=True, verbose_name='品牌名'),
        ),
    ]
