# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180405_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='订单号'),
        ),
    ]
