# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20180405_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
