# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180405_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='notes',
            new_name='post_script',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_mount',
            new_name='total_price',
        ),
    ]
